services:
  # backend:
  #   build: ./backend
  #   volumes:
  #     - ./backend/node_modules:/app/node_modules
  #   ports:
  #     - 5000:5000

  # mongo:
  #   image: mongo:6.0
  #   command: mongod --quiet --logpath /dev/null
  #   ports:
  #     - 27017:27017

  frontend:
    build: ./frontend
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true    
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/src:/app/src
    ports:
      - 3000:3000